project:
  type: website
  output-dir: docs

website:
  title: "Arun Krishnasamy | Portfolio"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/apkrishnasamy
      - icon: github
        text: GitHub
        href: https://github.com/ArunPrakash2901
      - text: Projects
        href: /projects/
      - text: Posts
        href: index.qmd
      - text: CV
        href: resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css