project:
  type: website
  output-dir: docs

website:
  title: "The Hidden Impact of Town Size on Youth Employment"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ArunPrakash2901
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

