---
title: "Week 4(creating blog)"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

**The Green Divide: How wealth buys shade in a warming world**

The article here is from Stuff news, titled “The Green Divide: How wealth buys shade in a warming world”, available online via [Stuff news website](https://interactives.stuff.co.nz/2022/03/urban-heat-island-tree-cover/).

This is a data journalism article, where a story created through examination of data to find trends and anomalies.

The article provides information about the uneven tree cover in New Zealand, oftentimes dictated by wealth. When the tree cover data and socio-economic data were visualised, affluent the area, the more tree canopy it owns. Furthermore, the article draws connection on how heritage contributes to green canopy and suburbs with lot of inaccessible greenery, such as hillside, might not provide shade to anyone.

The background for the article is in the first eight paragraphs. The article's background provides context for knowing the importance of tree cover in urban areas, especially about the urban heat island effect. It describes how trees reduce temperature in cities by transpiring water. There is also emphasis on how the presence of more trees in more prosperous areas results in unequal heat exposure. This background is crucial because it highlights the article's importance on the effects that the tree cover has on society and the environment.

The lede in the article is in the title, “How wealth buys shade in a warming world.” The author goes with two approaches of using the data to develop the content as well as backing up the story with the data. The article spans a narrative and takes the readers through a series of different case studies, explaining it clearly with annotated visualization.

The summary of the story is in the middle of the scrollable article:

“When *Stuff* combined the council tree canopy maps with socio-economic data, it bore out the link between wealth and leafiness. The next map simultaneously shows the level of tree canopy cover in each neighbourhood in Auckland and how wealthy the area is: the darkest areas on the maps are the leafiest, most prosperous neighbourhoods. The lightest areas are those with little canopy cover and the lowest level of wealth.”

This conveys reader the fact that, areas with prosperity tend to be leafy, compared to the less prosperous area. For conciseness, some information has been omitted, as it is assumed that the reader is aware of the story's bigger picture (cases of heritage and inaccessibility to greenery playing a role).

Although, the result here is iterated throughout the article, that wealth and tree cover is related; by visualizing the data, article ends with the tone of irrelevancy and then concludes encouraging the city council to take steps.

The author quotes,

“Canopy cover is measured because it’s really easy to measure but … all it gives you is a two-dimensional description. Any of that stuff around shading or transpirational cooling is related to leaf area — and canopy cover does not give you that.”

“If \[councils\] know that there are neighbourhoods that only have four per cent canopy cover, they would hopefully see it as their responsibility to increase canopy cover in that area.”
